version = 1

test_patterns = ["__tests__/**", "spec/**"]

exclude_patterns = ["packages/integration/fixtures/**"]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "shell"
enabled = true
