name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [8.x, 10.x, 12.x]
        include:
        - os: macos-latest
          node: 12.x

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ matrix.node-version }}-${{ env.cache-name }}-
          ${{ runner.OS }}-build-${{ matrix.node-version }}-
          ${{ runner.OS }}-build-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Java
      uses: olafurpg/setup-scala@v5
    - name: yarn install
      run: yarn install
    - name: yarn test
      run: yarn test
      env:
        CI: true
        
  sonarcloud:
    runs-on: ubuntu-latest
    if: github.repository == 'swissquote/crafty' && github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v1
    - name: Install Java
      uses: olafurpg/setup-scala@v5
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  documentation:
    runs-on: ubuntu-latest
    if: github.repository == 'swissquote/crafty' && github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v1
    - name: Cache vendor
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-docs-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.OS }}-docs-${{ env.cache-name }}-
          ${{ runner.OS }}-docs-
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Generate documentation
      run: vendor/bin/daux generate --themes=docs_theme
    - uses: JamesIves/github-pages-deploy-action@2.0.3
      env:
        FOLDER: "static"
        BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
